### ISSUE TITLE
allow hierarchical nested subdomains

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/dsd#18]
Currently, a Strand contains Domains.

Allow a Domain to contain subdomains. This would help to specific common motifs such as 2-base-pair "clamps", without having to introduce lots of new domains at the top level of the Design.

Another example: what if we have intended mismatches in a complex? We could partition into 3 subdomains: the length-1 mismatch, and the subdomains on either side.

Also "nested toeholds"... I'll let Chris explain this.

**Comment by dave-doty** [comment]
Idea for representing:

1. add a field `subdomains` to `Domain` class, of type `List[Domain]`
2. If `None`, then no subdomains
3. If not `None`, must be a list of length at least 2, and `sum(subdomain.length for subdomain in domain.subdomains) == domain.length`. These two constraints automatically enforce no cycles.
4. add method `Strand.subdomains(include_top_level: bool = True)` to recursively get all subdomains in the `Strand`, including the top-level `Domain`'s if `include_top_level` is True.
5. add method `Domain.all_subdomains(include_top_level: bool = True)` to recursively get all subdomains in the `Domain`, including `self` if `include_top_level` is True.
5. In pre-packaged constraints that evaluate `Domain`'s and `Strand`'s, blame all `Domain`'s in `Domain.all_subdomains()`, (respectively, `Strand.subdomains()`)

**Comment by UnHumbleBen** [comment]
Another reason for implementing hierarchical nested subdomains is to allow constraints to be written on "top-level" domains. For example, one of the requirements for the sequence design with seesaw circuits is that
>  For any two sequences in the pool, we require at least 30% of bases are different, and the longest run of matches
is at most 35% of the domain length.
> [Link to Paper](https://science.sciencemag.org/content/sci/suppl/2011/06/02/332.6034.1196.DC1/Qian.SOM.pdf)

Ideally, every sequence in the pool is of length 15. In this case, this constraint can be trivially implemented using `DomainPairConstraint`. However, in order to deal with the extended toehold needed for thresholding reactions, the pool is actually broken into two pools, one for the extended toehold, which is of length 2 and another pool for the rest of the sequence, which is of length 13. Since each logical "domain" now consist of two `Domain` objects, `DomainPairConstraint` is not sufficient.

**Comment by dave-doty** [comment]
I'm still considering whether this issue will solve such problems better than the following alternative:

Currently, we have one fixed notion of how a domain's sequence can depend on other. If domain `x` has a certain DNA sequence, then its starred version `x*` has the complement sequence.

We could extend this idea to customizable dependencies. For example, I could say something like, "*bases 4-7 on domain `x` must be the complement of bases 14-17 on domain `y`*", or "*the 5'-most base on `x` should **not** be the complement of the 3'-most base on `x*`*" (i.e., override the normal behavior and force a mismatch).

It seems like if we do this correctly, it could also let us handle what the "subdomains" in the "Scaling up..." paper would do.
